### ISSUE TITLE
Trouble testing random APIs

### ISSUE THREAD

**Issue by bucko13** [bpanel-org/curl#1]
Any idea why I can `GET` this: https://pokeapi.co/api/v2/pokemon/ditto
But if I do http://localhost:5000/curl/pokeapi.co/api/v2/pokemon/ditto I just get a blank bpanel page? Might just be I'm formatting the request incorrectly.

**Comment by pinheadmz** [comment]
It's because the endpoint is strictly `/curl/:host/:path` and any other extra slashes you request imply additional parameters. 

The secret is here: https://github.com/bpanel-org/price/blob/1986ddb644c09c38bb10e4d044c24b178b1c9a69/lib/feeds.js#L22

Try requesting this:
http://localhost:5000/curl/pokeapi.co/api%2Fv2%2Fpokemon%2Fditto

**Comment by bucko13** [comment]
Ah! Gotcha! I saw a feed with deeper paths and thought it supported that but I guess those got encoded first. Makes sense. Might be good to document that that needs to be encoded, and/or the path gets added as a query param as a way to kind of split it from the normal path? That feels a little more intuitive and possibly RESTful to me.
